version: "3"

services:
  dotnet:
    container_name: dotnet
    build:
      context: .
      dockerfile: ./docker/containers/dotnet/Dockerfile
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    environment:
      - ASPNETCORE_URLS=http://+:${SERVER_PORT}
      - ASPNETCORE_ENVIRONMENT=Production
    env_file:
      - .env
  
  nuxt:
    container_name: nuxt-nginx
    build:
      context: .
      dockerfile: ./docker/containers/nuxt-nginx/Dockerfile
    env_file:
      - .env
    depends_on:
      - dotnet
    ports:
      - ${CLIENT_PORT}:80
    environment:
      - API_URL
